### ISSUE TITLE
Feature: Signin

### ISSUE THREAD

**Issue by nyomansunima** [explore-box/doen#2]
# About

Create a sign-in page for the user to access the account. Allow the user to signing using many methods including:

- Email and password
- Github
- Google

## Tasks

Here are the tasks that need to complete

- [x] Create the UI design
- [x] Create the web form
- [x] Authenticate using email password
- [x] Create composable for query and mutation
- [x] Testing the app
- [x] Deploy

**Comment by nyomansunima** [comment]
Ok, create the ui design in figma

**Comment by nyomansunima** [comment]
Iam just confused about some composable and the form what i should choose

**Comment by nyomansunima** [comment]
Iam creating a backend using google, github, and email in nestjs using passport.js
